version: '3'
services:
  
  stratisd:
    build: ./stratisd
    image: stratisd:latest
    volumes:
      - breezeserver-shared-testnet-data:/home/shared
      - stratis-testnet-data:/data
    ports:
      - "127.0.0.1:26174:26174"
  bitcoind:
    image: kylemanna/bitcoind:latest
    volumes:
      - bitcoin-testnet-data:/bitcoin
      - "./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf"
    ports:
      - "127.0.0.1:18332:18332"
      - "8333:8333"
  tor:
    image: ./tor
    image: tor:latest
    volumes:
      - breezeserver-shared-testnet-data:/home/shared
      - ./breeze-tor.sh:/home/tor/breeze-tor.sh
    ports:
      - "9050:9050"
      - "127.0.0.1:9051:9051"
    command: /bin/bash /home/tor/breeze-tor.sh
  breezeserver:
    depends_on:
      - stratisd
      - bitcoind
      - tor
    build: ./breezeserver
    image: breezeserver:latest
    environment:
      # BreezeServer uses HOME to define application datadirs (.ntumblebitserver, .breezeserver)
      - HOME=/shared
    volumes:
      - breezeserver-shared-testnet-data:/home/shared

volumes:
  bitcoin-testnet-data:
  stratis-testnet-data:
  breezeserver-shared-testnet-data:
