version: '3'
services:
  bitcoind:
    image: kylemanna/bitcoind:latest
    volumes:
      - bitcoin-testnet-data:/bitcoin
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
    ports:
      - "127.0.0.1:18332:18332"
      - "8333:8333"

volumes:
  bitcoin-testnet-data:
