version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master

init:
  # Good practise, because Windows
  - cmd: git config --global core.autocrlf true
install:
  # need to do the recursive clone here for submodules
  git submodule update --init --recursive
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # 
  - cmd: dotnet restore ./BreezeServer.sln
build_script:
  #
  - cmd: dotnet publish ./BreezeServer.sln
after_build:
  # For once the build has completed
test_script:
  # tests in here
  - cmd: dotnet test ./Breeze.BreezeServer.Tests/Breeze.BreezeServer.Tests.csproj
  #- cmd: cd ..
on_finish :
  # any cleanup in here
deploy: off
